# -*- coding: utf-8 -*-
"""Ejemplo3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAmYbtLUv6GOhNCea5dQlGbYWXnu53YM
"""

import streamlit as st

st.write('Hello, *World!* :sunglasses:')